spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 20020421
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      sentinel:
        master: mymaster
        nodes: 127.0.0.1:26379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

aliyun:
  oss:
    bucket-name: hmleadnewsxu
    endpoint: https://oss-us-west-1.aliyuncs.com
