spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 20020421
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
aliyun:
  oss:
    bucket-name: hmleadnewsxu
    endpoint: https://oss-us-west-1.aliyuncs.com